stages:
  - test

test_app:
  tags:
   - python3
  image: python:latest
  stage: test
  before_script:
  - python -V
  - pip install virtualenv
  - virtualenv env
  - source env/bin/activate
  script:
  - pip install -r requirements.txt
  - python main.py
  - python3 -m unittest test_api.py 
